  - name: Start k8s head node
    local_action:
      module: cs_instance
      name: "{{ k8s_node_prefix }}-head"
      template: "{{ k8s_template }}"
      service_offering: "{{ k8s_instance_type }}"
      ssh_key: "{{ ssh_key }}"
      security_groups: [ '{{ k8s_security_group_name }}' ]
      user_data: "{{ lookup('template', '../templates/k8s-master.j2') }}"
    register: k8s_master
    
  - debug: msg='k8s master IP is {{ k8s_master.default_ip }}'
              
  - name: Start k8s nodes
    local_action:
      module: cs_instance
      name: "{{ k8s_node_prefix }}-node-{{ item }}"
      template: "{{ k8s_template }}"
      service_offering: "{{ k8s_instance_type }}"
      ssh_key: "{{ ssh_key }}"
      security_groups: [ '{{ k8s_security_group_name }}' ]
      user_data: "{{ lookup('template', '../templates/k8s-node.j2') }}"
    with_sequence: count={{ k8s_num_nodes }}
    register: k8s_nodes
