# Rules for the k8s security group

  - name: SSH for k8s
    local_action:
     module: cloudstack_sg_rule
     name: k8s
     start_port: 22
     end_port: 22

  - name: k8s 4001
    local_action:
     module: cloudstack_sg_rule
     name: k8s
     start_port: 4001
     end_port: 4001
     user_security_group: k8s

  - name: k8s 7001
    local_action:
     module: cloudstack_sg_rule
     name: k8s
     start_port: 7001
     end_port: 7001
     user_security_group: k8s

  - name: k8s 10250
    local_action:
     module: cloudstack_sg_rule
     name: k8s
     start_port: 10250
     end_port: 10250
     user_security_group: k8s

  - name: k8s UDP 8285
    local_action:
     module: cloudstack_sg_rule
     name: k8s
     start_port: 8285
     end_port: 8285
     protocol: udp
     user_security_group: k8s

  - name: k8s 8080
    local_action:
     module: cloudstack_sg_rule
     name: k8s
     start_port: 8080
     end_port: 8080
     user_security_group: k8s

